import re
# Class mapping: keyword rules on the raw `category` tag (case-insensitive, whole-tag regex), fallback = category_refined.
ESPORTS = r"esports|league of legends|counter strike|cs2|csgo|dota|valorant|call of duty|overwatch|rocket league|rainbow six|r6|mobile legends|starcraft|halo|apex|fortnite|pubg|honor of kings|arena of valor|ea sports fc|lck|lpl|worlds 20|msi|iem|blast|pgl|esl|vct|tekken|street fighter|smash|chess"
GEO = r"geopolitic|world elections|french election|french|^world$|iran|israel|gaza|ukrain|russia|middle east|foreign policy|venezuela|maduro|khamenei|pahlavi|mojtaba|hezbollah|hamas|houthi|hormuz|trade war|military|macro geopolitics|putin|zelensk|machado|saudi|ceasefire|china|kurd|lebanon|pakistan|thailand|cambodia|global elections|denmark|poland|france|canada|south korea|hungary|mexico|peru|japan|india|taiwan|north korea|syria|yemen|iraq|turkey|germany|uk |united kingdom|britain|europe|eu |nato|un |war|nuclear|greenland|davos|allah|argentina|brazil|chile|colombia|bolivia|ecuador|nigeria|south africa|australia|new zealand|philippines|indonesia|vietnam|egypt|cuba|haiti|serbia|kosovo|romania|bulgaria|czech|austria|netherlands|belgium|ireland|scotland|portugal|spain$|italy|greece|norway|sweden|finland|switzerland|starmer|macron|merz|modi|erdogan|netanyahu|xi |kim jong|lula|milei|sheinbaum|carney|albanese|world cup(?! )"
FIN = r"nymex|comex|spx|ndx|dji|rut|nik|hsi|ftse|nya|^fed|economy|commodit|^gold$|^oil$|crude|earnings|equities|stocks?$|treasur|inflation|macro indicator|s&p|pre-market|indicies|indices|nvda|amzn|tsla|aapl|googl|msft|^meta$|nflx|pltr|hood|^open$|microstrategy|business|big tech|ipos?$|jerome powell|exchange rate|prediction markets|tesla|apple|google|^coin$|finance|silver|natural gas|rates|gdp|cpi|jobs|unemployment|tariff|recession|interest rate|stock market|nasdaq|dow|market cap"
CRYPTO = r"crypto|bitcoin|btc|ethereum|eth$|solana|sol$|xrp|ripple|doge|bnb|token|airdrop|fdv|metadao|public sales|monad|megaeth|lighter|hyperliquid|zama|makina|vooi|^base$|ethgas|satoshi|stablecoin|ath$|up or down|^5m$|^15m$|^1h$|^4h$|weekly|hit price|daily-close|price action|multi strikes|daily strikes|today|recurring|hide from new|pump|memecoin|defi|nft|binance|coinbase|kraken|polymarket|opensea|uniswap|aave|chainlink|link$|cardano|ada$|avalanche|avax|polkadot|litecoin|tron|sui$|aptos|arbitrum|optimism|zk|berachain|abstract|plasma|linea|scroll|blast|jupiter|pengu|hype$|world liberty|wlfi|trump coin|melania|ondo|ena$|pendle|eigen|sei$|ton$|near$|inj$|tia$|dydx|gmx|starknet|kaito|virtuals|ai16z|pudgy|moonbirds|bored ape|punks"
SPORTS = r"sports?|^games$|uef qualifiers|africa cup|^lmb$|nba|nfl|nhl|mlb|cfb|ncaa|epl|premier league|la liga|serie a|bundesliga|ligue 1|ufc|boxing|tennis|cricket|soccer|football|basketball|baseball|hockey|golf|formula 1|f1$|mma|wbc|a-league|professional league|winter games|olympic|super bowl|playoffs|champions league|europa|mls|rugby|darts|snooker|cycling|nascar|wrestling|wwe|ryder cup|atp|wta|masters|pga|kentucky derby|tyson fury|big game|game specials|game props|parlays|world series|stanley cup|march madness|final four|heisman|nba draft|nfl draft|liga mx|eredivisie|copa|euro 20|afcon|ipl|t20|ashes|wimbledon|us open|french open|australian open|grand slam|marathon|ncaaf|ncaab|xfl|cfl|afl|nrl|super rugby|handball|volleyball|table tennis|badminton|swimming|athletics|world athletics|tour de france|giro|vuelta|motogp|indycar|24 hours|le mans|fifa|uefa|conmebol|concacaf|fight|bellator|pfl|one championship|glory|bare knuckle|bkfc|jake paul|canelo|usyk|joshua|mike tyson|lakers|celtics|warriors|knicks|yankees|dodgers|chiefs|eagles|cowboys|packers|49ers|bills|ravens|lions|real madrid|barcelona|man city|manchester|liverpool|arsenal|chelsea|tottenham|bayern|psg|juventus|inter|milan|dortmund|atletico|ohtani|messi|ronaldo|lebron|curry|mahomes|djokovic|alcaraz|sinner|swiatek|sabalenka|gauff|verstappen|hamilton|norris|leclerc|scheffler|mcilroy|golden globe"
CULTURE = r"culture|badbunny|bad bunny|magazine|tweet markets|time person|movies?|film|tiktok|mrbeast|music|celebrit|youtube|eurovision|oscars|awards|grammy|emmy|tony|box office|netflix|hbo|disney|marvel|star wars|taylor swift|kanye|^ye$|drake|kendrick|beyonce|rihanna|billboard|spotify|streaming|reality tv|survivor|bachelor|love island|big brother|the traitors|jeopardy|wordle|pokemon|gta|video games|nintendo|playstation|xbox|steam|twitch|kick|streamer|influencer|podcast|joe rogan|elon|kardashian|royal|prince|king charles|meghan|harry|pope|papal|conclave|religion|christmas|thanksgiving|halloween|super bowl halftime|met gala|fashion|met|art|book|novel|nobel|pulitzer|time person|word of the year|barbie|mario|anime|manga|k-pop|bts|blackpink|comedy|snl|late night|ufo|aliens"
POLITICS = r"politic|trump|elections?|nyc|united states|economic policy|polls?|congress|courts?|shutdown|mamdani|nyc mayor|sliwa|epstein|comey|mentions|senate|house|governor|mayor|primary|midterm|president|vance|biden|harris|obama|democrat|republican|gop|dnc|rnc|supreme court|scotus|impeach|cabinet|doge$|federal|executive order|pardon|tariff|immigration|ice$|deport|border|minnesota unrest|sotu|state of the union|approval|poll|fbi|cia|doj|attorney general|bondi|hegseth|rubio|musk|rfk|kennedy|newsom|desantis|abbott|hochul|adams|cuomo|schumer|jeffries|johnson|thune|mcconnell|pelosi|aoc|ocasio|bernie|warren|fetterman|manchin|sinema|kirk|charlie kirk|extend|enrich|strike$|skr|prize|opinion|derivatives|parent for derivative|featured|^us$|u\.s\. politics|brown university|rewards"
OTHER = r"weather|climate|hurricane|snow|temperature|earthquake|volcano|tech|^ai$|science|spacex|openai|anthropic|claude|nvidia|gemini|chatgpt|grok|llm|pandemic|aliens|ufo|transit|free solo|space|nasa|list|2025 predictions|2026 predictions"
def _wrap(rx):
    out=[]
    for alt in rx.split("|"):
        a=alt
        if not a.startswith("^"): a=r"\b"+a
        core=alt.strip("^$")
        if not a.endswith("$") and len(core)<=4: a=a+r"\b"
        out.append(a)
    return "|".join(out)
RULES=[("esports",_wrap(ESPORTS)),("geopolitics_world",_wrap(GEO)),("sports",_wrap(SPORTS)),("finance",_wrap(FIN)),("crypto",_wrap(CRYPTO)),("other",_wrap(OTHER)),("culture",_wrap(CULTURE)),("politics",_wrap(POLITICS))]
REFINED={"Sports":"sports","Price Action":"crypto","Crypto":"crypto","Politics":"politics","Culture":"culture","Finance":"finance","Sci-Tech":"other","Other":"other"}
def map_class(category, refined):
    c=(category or "").strip().lower()
    for cls,rx in RULES:
        if re.search(rx,c): return cls, "keyword"
    return REFINED.get(refined,"other"), "refined_fallback"
def subclass(category, refined, cls):
    if cls=="crypto":
        return "crypto_updown" if (refined=="Price Action" or re.search(r"up or down|^5m$|^15m$|^1h$|^4h$|hit price|daily-close|multi strikes|daily strikes|weekly|today|recurring|hide from new|crypto prices",(category or "").lower())) else "crypto_other"
    return cls
