import pandas as pd, numpy as np
SC='/tmp/claude-1000/-home-sowelo-Scrivania-IntelliFi-anomaly-detection/1ca1568e-3e0a-4271-965d-872ec4a24b54/scratchpad/atlasC'
def _tbl(d):
    cols=list(d.columns)
    lines=['| '+' | '.join(str(c) for c in cols)+' |', '|'+'|'.join(['---']*len(cols))+'|']
    for _,r in d.iterrows(): lines.append('| '+' | '.join('' if (isinstance(v,float) and pd.isna(v)) else str(v) for v in r.values)+' |')
    return '\n'.join(lines)
def md(df, cols, fmt=None, index=False):
    d=df[cols].copy()
    for c in d.columns:
        if fmt and c in fmt: d[c]=d[c].map(lambda v: '' if pd.isna(v) else fmt[c].format(v))
    if index: d=d.reset_index()
    return _tbl(d)
M=lambda v: f"{v/1e6:,.1f}"
q5m=pd.read_csv(f'{SC}/q5_ctf_monthly.csv'); q5f=pd.read_csv(f'{SC}/q5_fills_monthly.csv'); q5c=pd.read_csv(f'{SC}/q5_ctf_by_class.csv'); q5y=pd.read_csv(f'{SC}/q5_ctf_yearly.csv'); q5r=pd.read_csv(f'{SC}/q5_reconciliation_monthly.csv'); q5fc=pd.read_csv(f'{SC}/q5_fills_by_class.csv')
q6a=pd.read_csv(f'{SC}/q6a_platform.csv'); q6c=pd.read_csv(f'{SC}/q6a_corpus.csv'); q6b=pd.read_csv(f'{SC}/q6b_monthly.csv'); q6bc=pd.read_csv(f'{SC}/q6b_2026_by_class.csv'); q6bp=pd.read_csv(f'{SC}/q6b_2026_pooled_by_class.csv'); ov=pd.read_csv(f'{SC}/q6b_2026_top10_overlap.csv')
for d in (q5m,):
    d['split_M']=d.split_usd/1e6; d['exch_M']=d.split_exch/1e6; d['nr_M']=d.split_nradapter/1e6; d['ada_M']=d.split_ada/1e6; d['oth_M']=d.split_other/1e6; d['merge_M']=d.merge_usd/1e6; d['redeem_M']=d.redeem_usd/1e6; d['fill_M']=d.fill_usd/1e6
q5f['x_row_share']=q5f.n_rows_x/q5f.n_rows; q5f['x_sh_share']=q5f.sh_x/q5f.sh; q5f['x_sell_sh_share']=q5f.sh_x_sell/q5f.sh; q5f['x_buy_sh_share']=q5f.sh_x_buy/q5f.sh; q5f['samedir']=q5f.n_rows_x_samedir/q5f.n_rows
q5fc['x_row_share']=q5fc.n_rows_x/q5fc.n_rows; q5fc['x_sh_share']=q5fc.sh_x/q5fc.sh; q5fc['x_sell_sh_share']=q5fc.sh_x_sell/q5fc.sh
q5c=q5c.copy(); 
for c in ['split_usd','split_exch','split_nr','split_ada','split_other','merge_usd','redeem_usd','fill_usd']: q5c[c+'_M']=q5c[c]/1e6
q5y=q5y.rename(columns={q5y.columns[0]:'yr'})
for c in ['split_usd','split_exch','split_nradapter','split_ada','split_other','merge_usd','redeem_usd','fill_usd']: q5y[c+'_M']=q5y[c]/1e6
q5r['exch_split_M']=q5r.split_exch/1e6; q5r['sh_x_sell_M']=q5r.sh_x_sell/1e6; q5r['sh_M']=q5r.sh/1e6
f3={'mint_to_fill':'{:.3f}','exch_mint_to_fill':'{:.3f}','merge_to_fill':'{:.3f}','redeem_to_fill':'{:.3f}'}
fM={c:'{:,.1f}' for c in ['split_M','exch_M','nr_M','ada_M','oth_M','merge_M','redeem_M','fill_M','exch_split_M','sh_x_sell_M','sh_M']}
fM.update({c+'_M':'{:,.1f}' for c in ['split_usd','split_exch','split_nr','split_nradapter','split_ada','split_other','merge_usd','redeem_usd','fill_usd']})
pct={c:'{:.1%}' for c in ['x_row_share','x_sh_share','x_sell_sh_share','x_buy_sh_share','samedir','top10_share','top10_fill_share','top1_share','top50_share','hhi','persistence','frac_wrong_side','frac_within_5c','exch_mint_share_of_shares']}
pct['hhi']='{:.4f}'; pct['persistence']='{:.1f}'
r3={c:'{:.3f}' for c in ['med','mean','p90','ratio_split_exch_over_sh_x_sell','ratio_merge_exch_over_sh_x_buy']}
F={**f3,**fM,**pct,**r3}
q6a['n_markets']=q6a.n_markets.astype(int); q6a['n_with_fill']=q6a.n_with_fill.astype(int)
A=q6a[q6a.cut=='all']; C=q6a[q6a.cut=='class']; E=q6a[q6a.cut=='early']; N=q6a[q6a.cut=='notional']
q6b['eff_n']=1/q6b.hhi
out=[]
w=out.append
w("# Polymarket structural atlas — Q5 (share creation vs. secondary trading), Q6a (resolution-anchored convergence), Q6b (maker concentration)\n")
w("Author: agent C (struct_*). Date: 2026-08-30. Data: public Polymarket-v1 archive (arXiv:2606.04217, CC-BY-4.0) at `data/external/polymarket_v1/` — `daily_aligned` (binary) + `daily_aligned_multi` (negRisk) maker-fill files 2022-11-21 → 2026-04-28, plus `CTF/{preparations,splits,merges,resolutions,redemptions}.parquet`. No external API was called. Everything was computed with `.venv/bin/python` + DuckDB, one daily file (or one CTF block-range chunk) per SQL statement, results written to parquet immediately, `PRAGMA memory_limit='4GB'`, `PRAGMA threads=4`, `PRAGMA temp_directory=<scratch>/duck_tmp`, each process additionally wrapped in `systemd-run --user --scope -p MemoryMax=6G -p MemoryHigh=5G timeout 520`. Outputs: `data/parquet/atlas/struct_*.parquet` (19 files, 3.9 GB) and CSV/log files in the scratch dir `atlasC/`.\n")
w("## 0. Corpus and semantics established before answering\n")
w("""* Tape: **745,781,095 maker-fill rows** (601,713,694 binary + 144,067,401 negRisk), **$28,577,595,925** fill notional (Σ `usdc_amount`), **851,083 markets** (687,814 binary, 163,269 negRisk), 1,235,715 distinct makers. Row-count and notional totals of every derived table reconcile exactly to these figures (checked: `struct_condmonth`, `struct_maker_month`, `struct_mintgroups_condmonth`).
* Archive semantics, verified against the project's own tx-level on-chain fills (`data/parquet/fills/`, 5 markets, 276,837 OrderFilled rows): one row = one **maker** fill; `asset_id`/`price` are the **maker's** token and limit price; `taker_direction` is the taker's side *as counterparty of that maker* (so a maker who BUYs the complementary token appears as `taker_direction='SELL'` on that token). For the one market joined leg-by-leg (`0x4dce…`, 1,040 maker fills) 247/247 complement legs and 817/817 same-token legs matched the on-chain fills on (maker, taker, second, shares) with the archive's `asset_id` equal to the **maker's** token. Mint/merge legs are therefore not "hidden"; they simply sit on the complementary token with price ≈ 1 − taker price (median p₁+p₂ = 1.000 in same-second groups).
* `resolution_status`: resolved 843,335, pending 525, disputed 12, NULL 7,211. `resolved_at` is non-NULL for **313,026** markets only — all binary; **0 of 158,910 resolved negRisk markets** carry it, and 99.3 % of the non-NULL values are markets resolved in 2026-01…05 (Gamma only started populating it recently). Fills after `resolved_at`: 0 (checked on sample days). Fills after `close_at`: common (7–30 % of a day's rows) — `close_at` is a scheduled deadline, never used as a close here.
* Category classes: the binary files carry an 8-class `category_refined` (Sports, Politics, Crypto, Price Action, Finance, Culture, Sci-Tech, Other; "Price Action" = short-horizon crypto up/down markets). The negRisk files carry only the fine tag. Mapping (`struct_category_classmap.parquet`): a tag's class = the notional-weighted majority class it has in the binary files (1,470 tags → 842,663 markets, $27.88 B, "archive" source); 107 negRisk-only tags ($207 M, 3,521 markets) by keyword rule; 323 tags ($488 M, 4,899 markets, largest: `january 6` $226 M/3 markets, `United States` $143 M) unmapped → "Other". Class totals: Sports $10.98 B (419,511 mkts), Politics $6.76 B (35,391), Crypto $3.89 B (123,894), Price Action $3.18 B (189,791), Other $1.39 B (16,946), Finance $1.02 B (18,608), Culture $0.89 B (12,742), Sci-Tech $0.46 B (34,200).
* CTF events have block numbers but no timestamps. A block→time map was built from the fill tape without any external call: for each 10k-block bin, the intercept of `t − 2.2·block` is bracketed from above by the earliest first-fill of conditions *prepared* in the bin and from below by the latest last-fill of conditions *resolved* in the bin (2,127 bins bracketed within [−1 h, +2 h]); spikes removed, gaps interpolated; the tail (blocks ≥ 85.0 M, where the tape's own anchors thin out) uses the medians of Gamma `resolved_at` per bin (+214 s, the measured on-chain lag). **Validation on 313,026 resolutions:** on-chain resolution time − Gamma `resolved_at` = median +216 s, IQR +84…+457 s, p1/p99 −2,281/+2,580 s; implied block time 2.0–2.33 s. Month boundaries were converted to blocks with this map; the "April 2026" CTF month is cut at the tape's end (2026-04-29 00:00 UTC) so CTF and fill windows coincide. Collateral restricted to USDC.e, native USDC and the negRisk wrapped collateral (a WMATIC row with 1.0e12 "USDC" and 100+ spam tokens were excluded); `parent_collection_id` = 0 only (6 rows excluded).
""")
w("## Q5 — Share creation (CTF splits) vs. secondary trading (fill notional)\n")
w("### Q5.1 Monthly CTF flows vs. fill notional, 2023-01 → 2026-04 (USDC millions; `exch` = CTF-Exchange stakeholder = mint/merge matches in binary markets; `nr` = NegRiskAdapter stakeholder = negRisk exchange matches **plus** user splits and negRisk conversions; `ada` = two Polymarket vanity contracts `0xADa100…`/`0xAdA100D…` active from 2026-04; `oth` = 109k other stakeholders, i.e. wallets splitting directly on the CTF)\n")
w(md(q5m,['ym','split_M','exch_M','nr_M','ada_M','oth_M','merge_M','redeem_M','fill_M','mint_to_fill','exch_mint_to_fill','merge_to_fill','redeem_to_fill'],F)); w("")
w("Totals 2023-01 → 2026-04: splits **$58,248 M** (exch 24,943 · nr 29,719 · ada 62 · other 3,525), merges **$11,525 M** (exch 2,010 · nr 6,566), redemptions **$28,505 M**, fill notional **$28,577 M** → **mint/fill = 2.038**, exchange+adapter mint/fill = 1.913, merge/fill = 0.403, redeem/fill = 0.997. All-time (2022-11 → 2026-05) splits are $63,648 M, of which $10,003 M sit on 449k condition-months that are absent from the fill tape (conditions never traded on the CLOB or outside the tape's coverage).\n")
w("Yearly:\n"); w(md(q5y,['yr','split_usd_M','split_exch_M','split_nradapter_M','split_other_M','merge_usd_M','redeem_usd_M','fill_usd_M','mint_to_fill','exch_mint_to_fill','merge_to_fill','redeem_to_fill'],F)); w("")
w("Reading: (i) the 2023 ratios are dominated by a handful of 'other' stakeholders splitting directly on the CTF ($19.5 M in 2023-01 against $0.55 M of fills — early liquidity provisioning); exchange-driven minting alone was 1.0–1.7× fill notional in 2023. (ii) From 2024 on, exchange-driven minting is **1.6–3.5× the fill notional every month** (2024: 1.95; 2025: 2.12; 2026: 1.78). Since a mint of N pairs books only the *maker's* leg (≈(1−p)·N) into the archive's notional, a mint/fill ratio near 2 means that roughly all traded collateral is created by the exchange rather than transferred. (iii) Redemptions ≈ 1.0× fill notional over the window (0.33 in 2024 when the election money was still locked; 1.18 in 2025 as it was paid out).\n")
w("### Q5.2 By class (2023-01 → 2026-04)\n"); w(md(q5c,['cls','split_usd_M','split_exch_M','split_nr_M','split_other_M','merge_usd_M','redeem_usd_M','fill_usd_M','mint_to_fill','exch_mint_to_fill','merge_to_fill','redeem_to_fill'],F)); w("")
w("Mint/fill by class and year (NaN = class has no fills that year):\n"); pv=pd.read_csv(f'{SC}/q5_ctf_by_class_year.csv').pivot(index='cls',columns='yr',values='mint_to_fill').round(3).reset_index(); pv.columns=[str(c) for c in pv.columns]; w(_tbl(pv)); w("")
w("Sports and Crypto are the least mint-intensive (1.60, 1.39); Politics, Culture, Sci-Tech and 'Other' the most (2.07–2.76) — long-dated markets where both sides are bought and held rather than flipped. Politics' merge/fill (0.54) and 'Other' (1.09) are far above Sports (0.29): position unwinds in political markets go through merges (both sides sold) much more than in sports.\n")
w("### Q5.3 Fills-only identification (same-second complement rule) — monthly lower bound\n")
w("Rule: a maker fill is flagged as a mint/merge leg when, for the same (taker, block_timestamp, condition), rows exist on **both** outcome tokens with opposite `taker_direction` (`n_grp_x`); its shares are counted on the taker-`SELL` side (= maker BUY = mint) or the taker-`BUY` side (= maker SELL = merge). Groups with both tokens but the same direction (1.7 % of rows) and mixed groups (≥3 (token,direction) combinations, 1.0 %) are reported separately and not counted.\n")
w(md(q5f,['ym','n_rows','x_row_share','x_sh_share','x_sell_sh_share','x_buy_sh_share','samedir'],{**F,'n_rows':'{:,.0f}'})); w("")
w("Window totals: 174,147,458 of 745,779,356 rows (**23.35 %**) are in cross-token groups; 21.29 B of 75.85 B shares (**28.07 %**), of which 13.46 B (17.74 %) on the mint-consistent side and 7.84 B (10.33 %) on the merge-consistent side. By class (row share): Culture 29.7 %, Finance 27.0 %, Price Action 25.8 %, Politics 25.7 %, Crypto 23.4 %, Sci-Tech 23.1 %, Other 19.4 %, Sports 13.9 %; binary 24.8 % vs negRisk 17.4 %.\n")
w("### Q5.4 Reconciliation with CTF splits — the fills-only rule is a lower bound by a factor ≈2.7\n")
w("""* **Exact identity at the transaction level.** On the 5 markets with tx-level on-chain fills the CTF-Exchange split amount equals, to the cent, Σ shares of maker fills whose token is the complement of the taker's token *and* whose maker side is BUY: 149,334,390.77 = 149,334,390.77 (`0x6d0e…`), 21,374,085.72 = 21,374,085.72 (`0x8134…`), 6,720,630.10 = 6,720,630.10 (`0x42d8…`); merges equal the complement legs with maker SELL (21,264,770.69; 791,496.71; 2,085,029.21). So "minted collateral = complement-leg shares" is the right accounting, and the archive carries every leg.
* **True complement-leg share in those markets:** 54.2 % of maker fills / 63.4 % of shares (`0x6d0e…`, 137,451 maker fills), 65.8 % / 77.0 % (`0x8134…`), 51.8 % / 52.2 % (`0x42d8…`); two small negRisk markets 20.9 % / 0.9 % and 21.6 % / 0.2 %. Applying the same-second rule to those same on-chain maker fills flags only **37.3 % of rows / 35.2 % of shares** — the rule cannot see a taker order whose *every* leg is a complement leg (a single-token group), and those are the majority of mint matches.
* **Platform-wide (binary markets, all-time):** CTF-Exchange splits 24,938,050,278 share-pairs vs. 9,070,206,959 mint-consistent cross-group shares → **ratio 2.749**; merges 2,009,777,764 vs. 3,944,137,479 merge-consistent shares → 0.510 (merge-side groups also contain mint groups' normal legs). Per condition (199,602 binary conditions with ≥1,000 cross shares): median ratio 3.91, IQR 2.60–6.55, Pearson r = 0.943; only 0.8 % of conditions within ±10 %.
* **Implied true figure (binary):** mint legs = 24.94 B / 37.84 B = **65.9 %** of all maker-fill shares, merge legs 5.3 % → **≈71 % of binary share volume is share creation or destruction by the exchange; ≈29 % is a transfer of existing tokens.** Monthly, exchange mints alone are 45–78 % of binary shares (`exch_mint_share_of_shares` below). For negRisk the adapter's splits (27.22 B vs 38.01 B shares, 71.6 %) are an upper bound because the NegRiskAdapter is the CTF stakeholder for exchange matches, user splits and conversions alike; the NegRisk exchange never appears as a stakeholder.
""")
w(md(q5r,['ym','sh_M','sh_x_sell_M','exch_split_M','ratio_split_exch_over_sh_x_sell','ratio_merge_exch_over_sh_x_buy','exch_mint_share_of_shares'],F)); w("")
w("**Verdict Q5: publishable** — with the CTF split/merge amounts as the primary measure (monthly, by class, 40 months, exact tx-level identity), and the tape-only same-second rule reported as a lower bound with a measured 2.7× under-identification. Not supported: separating exchange-driven from user-driven minting inside negRisk.\n")
w("## Q6a — Resolution-anchored convergence platform-wide\n")
w("Method: winning token = the `asset_id` whose `outcome_label` equals `winning_outcome_label`; for each horizon the last fill of that token at or before `resolved_at − h`; error = |1 − price|. Sample: `resolution_status='resolved'` **and** non-NULL `resolved_at`. **Exclusions:** of 843,335 resolved markets, **530,309 (62.9 %) have NULL `resolved_at` and were excluded** — all 158,910 negRisk markets and 371,399 binary ones; of the 313,026 usable markets, 50,414 have no fill on the winning token (winner never traded / label mismatch) and 0 have two 'winning' tokens, leaving **262,612 markets** (Price Action 146,446 · Sports 62,945 · Crypto 47,113 · Finance 2,666 · Politics 2,044 · Other 623 · Culture 463 · Sci-Tech 312); 26,984 (10.3 %) resolved **before** `close_at` ('early'). `n_with_fill` is the number of markets that have any fill at or before the horizon (a 15-minute market has none 1 h before); statistics are over those markets only.\n")
w("### Q6a.1 All usable markets\n"); w(md(A,['horizon','n_markets','n_with_fill','med','mean','p90','frac_wrong_side','frac_within_5c'],F)); w("")
w("### Q6a.2 By class\n"); w(md(C,['grp','horizon','n_with_fill','med','mean','p90','frac_wrong_side','frac_within_5c'],F)); w("")
w("### Q6a.3 Early (resolved before `close_at`) vs. at/after `close_at`\n"); w(md(E,['grp','horizon','n_markets','n_with_fill','med','mean','p90','frac_wrong_side','frac_within_5c'],F)); w("")
w("### Q6a.4 By market notional\n"); w(md(N,['grp','horizon','n_markets','n_with_fill','med','mean','p90','frac_wrong_side','frac_within_5c'],F)); w("")
w("""Reading: at `resolved_at` itself (h0) the winner's last price is within 5 cents of 1 in 87.9 % of markets (median |1−p| = 0.010, p90 = 0.11), but 3.9 % of markets' last trade is on the wrong side (|1−p| > 0.5). One hour before resolution the distribution is bimodal: median 0.001 but mean 0.195, p90 0.51, 9.8 % wrong side. The bimodality is structural, not noise: Sports resolves minutes after the game (h1 median 0.001, h6 median 0.46 = in-play), Price Action markets (crypto up/down) resolve at a clock time and are coin-flips until the last minutes (h1 median 0.51, h0 0.010), while Finance (h1 median 0.002, p90 0.28) and Politics (h1 0.011, p90 0.52, 10.5 % wrong side even 1 h before) keep genuine uncertainty to the end. 'Early' resolutions converge *better* at h1 (median 0.001, p90 0.20, 4.7 % wrong side) than deadline resolutions (0.020, 0.51, 10.4 %): early resolution happens because the outcome became known. Large markets (≥$100k): h0 median 0.001, p90 0.010, 99.5 % within 5 cents; but 21.6 % wrong side at h1 — those are in-play sports and price-action markets.
""")
w("### Q6a.5 Consistency check on the 100-market corpus (`data/snapshots/20260829/corpus_condition_ids.txt`)\n")
w("97 of 100 conditions are in the archive (6,087,176 fills). Only **1** carries an archive `resolved_at`; the other anchors are the snapshot's Gamma `closed_time` (the project's own convergence anchor) and the CTF `ConditionResolution` block converted with the block→time map (`res_t_hat`). Snapshot `closed_time` − CTF time: median −262 s (p10 −97,428 s: for a few markets Gamma closed the book long before the on-chain payout report).\n")
w(md(q6c,['anchor','horizon','n_markets','n_with_fill','med','mean','p90'],{**F,'med':'{:.4f}','mean':'{:.4f}','p90':'{:.4f}'})); w("")
w("**h1 median = 0.001 for all 97 markets with either anchor — the expected ≈0.001 is reproduced**, and the CTF-block anchor gives the same numbers as Gamma's `closed_time` at every horizon (h1 0.001/0.001, d1 0.002/0.002, d7 0.007/0.007), which validates the block→time map as a resolution anchor to well within an hour.\n")
w("**Verdict Q6a: needs more.** The numbers are exact for the sample the archive allows, but that sample is 37 % of resolved binary markets, 0 % of negRisk, and 99 % 2026 resolutions — it is a 2026 short-horizon (Price Action + Sports) sample, not the platform's history. The corpus check passes. The fix is in hand: the CTF resolution block gives a resolution time for every one of the 841,272 resolved conditions (validated median +216 s vs Gamma), but re-anchoring the tape to it needs one more pass over the 16 GB tape (not run here to respect the memory/time constraints).\n")
w("## Q6b — Maker concentration platform-wide\n")
w("Method: from `struct_maker_month` (per month × maker: fills, Σ `usdc_amount`) — distinct makers and takers, HHI = Σ sᵢ² of maker notional shares, top-10 share of maker notional, share of *fills* whose maker is in that month's top-10, `eff_n` = 1/HHI, persistence = fraction of the month's top-10 makers that were top-10 in the previous month. 'Maker volume' is the notional of maker-fill rows (all rows); a maker appearing on the complementary leg of a mint counts on that token.\n")
w(md(q6b,['ym','n_makers','n_takers','n_fills','hhi','eff_n','top1_share','top10_share','top50_share','top10_fill_share','persistence'],{**F,'n_fills':'{:,.0f}','eff_n':'{:,.0f}','n_makers':'{:,}','n_takers':'{:,}'})); w("")
w("""Reading: the maker side went from an oligopoly — 142 makers, HHI 0.073, top-10 = 69.3 % of maker notional and 46.7 % of fills in 2023-01; 14 'effective' makers — to a long tail: 107,724 makers and HHI 0.0020 by 2024-12 and 254k–346k makers, HHI 0.0018–0.0025, top-10 share 8.7–11.5 %, top-1 share 1.3–2.5 % in 2026. The top-10 makers' share of *fills* is far below their share of notional (1.1–4.7 % vs 8.7–11.5 % in 2026; 46.7 % vs 69.3 % in 2023-01): large makers trade size, not frequency. Persistence of the top-10 collapsed from 0.7–0.9 (2023 H2) to 0.1–0.7 (2025–26, mean 0.40): the identity of the top-10 changes by more than half each month. Makers/takers ratio: 0.36 (2023-01) → 0.47 (2026-03).
""")
w("### Q6b.1 2026 by class, monthly\n"); w(md(q6bc,['ym','cls','n_makers','n_takers','hhi','top1_share','top10_share','top10_fill_share','persistence'],{**F,'n_makers':'{:,}','n_takers':'{:,}'})); w("")
w("### Q6b.2 2026 (Jan–Apr pooled) by class\n"); w(md(q6bp,['cls','n_makers','hhi','top10_share','top10_fill_share'],{**F,'n_makers':'{:,}'})); w("")
w(f"Politics is the most concentrated class by notional (pooled HHI 0.0058, top-10 = 19.6 %; monthly top-10 up to 30.2 % in 2026-04 with a single maker at 7.5 %), yet its top-10 make only 1.8 % of fills — a few large political market-makers. Sports and Price Action top-10 take 10–11 % of fills (high-frequency quoting bots). Cross-class overlap among the 80 pooled top-10 seats: one maker (`0xC8ab…6418`) is top-10 in five classes (Culture, Finance, Other, Politics, Sci-Tech), two more in four; the Sports/Price-Action/Crypto top-10s are disjoint from the political/cultural ones except two makers spanning Crypto+Price Action.\n")
w("**Verdict Q6b: publishable** — 40 consecutive monthly observations of the full maker population with exact totals; the class split covers 2026 only (the per-class maker table was only accumulated for 2026 to bound memory).\n")
w("## Caveats\n")
w("""1. **Maker-fill rows.** Every statistic is over maker fills; the taker-order aggregate is not a row. Notional counts the maker leg of a mint at the complementary price (≈(1−p)·N), so 'fill notional' is not the taker's cash — that is precisely why mint/fill ≈ 2 (Q5.1).
2. **Mint/merge identification from the tape alone is a lower bound** (Q5.4): 23.4 % of rows / 28.1 % of shares flagged vs. a CTF-implied 65.9 % of shares being mint legs in binary markets. Any paper that reports 'wash-like' same-second cross-token activity from this tape is measuring exchange mints.
3. **`resolved_at` NULL = unknown.** 530,309 resolved markets (62.9 %) — every negRisk market and most pre-2026 binary markets — were excluded from Q6a and never substituted with `close_at`. Q6a is therefore a 2026 sample dominated by 15-minute/hourly crypto markets and sports.
4. **Category granularity.** Tags are event-level marketing tags (1,900 distinct); the 8-class scheme follows the archive's own `category_refined`; 4,899 negRisk markets ($488 M, 1.7 % of notional) could not be classed and sit in 'Other', which also contains real 'Other'. 'Price Action' is a crypto subclass and is kept separate because its microstructure (clock resolution, 15-minute horizon) is different.
5. **Block→time map** is tape-derived (no RPC). Monthly assignment of CTF events is safe (validated ±40 min at p1/p99); April 2026 is cut at the tape end. CTF stakeholder classes: `0x4bFb…` CTF Exchange, `0xd91E…` NegRiskAdapter, `0xC5d5…` NegRisk Exchange (never a stakeholder), `0xADa100…`/`0xAdA100D…` unidentified Polymarket vanity contracts active from 2026-04 (splits $162 M in April 2026), 'other' = 109k distinct addresses.
6. **Universe coverage.** $10.0 B of all-time splits and $5.1 B of redemptions are on conditions absent from the fill tape; ratios are computed on tape conditions only.
7. **2026-04 is partial** (tape ends 2026-04-28) for both fills and CTF.
8. Memory bound used for every process: DuckDB `memory_limit='4GB'`, `threads=4`, spill to scratch; systemd `MemoryMax=6G`. Pass A runs were killed twice by session restarts and once for memory before the streaming rewrite; all monthly outputs were regenerated from complete inputs and reconcile exactly to the tape totals.
""")
w("## Novelty vs. cited work\n")
w("""* **arXiv:2603.03136** (2024 election market: proper volume accounting, share creation vs trading, Kyle's λ) — one market. Here: 40 months, 851k markets, every CTF split/merge/redemption attributed to stakeholder class and market class; exact tx-level identity between exchange splits and complement legs; the finding that ≈2/3 of binary share volume is exchange minting and that the public tape under-identifies it 2.7× is new.
* **arXiv:2604.24366** (eight stylised facts, 600 markets, 52 days, 'concentrated maker diversity') — a 52-day cross-section. Here: monthly maker HHI/top-10/persistence for 40 months and 1.24 M makers; the transition from a 14-effective-maker oligopoly (2023) to a 400–560-effective-maker tail (2026), the notional-vs-fill-share wedge, and per-class concentration are new.
* **arXiv:2602.19520** (domain-specific calibration) — calibration of prices vs outcomes. Here: not calibration but *time-to-resolution* convergence anchored on the resolution instant, split early-vs-deadline and by class; the bimodal h1 distribution and the coverage warning about `resolved_at` are new, but the sample limitation (Q6a verdict) must be fixed before publication.
* **arXiv:2606.04217** (the archive paper, classifier benchmarks) — documents the tape. Here: independent verification of its leg semantics against on-chain fills and the measurement that its same-second structure cannot recover mint legs.
""")
w("## One-line verdicts\n")
w("* **Q5** — publishable (CTF-anchored; tape-only rule = lower bound ×2.7; negRisk exchange-vs-user minting not separable).\n* **Q6a** — needs more (exact on 262,612 markets, but 63 % of resolved markets excluded for NULL `resolved_at`, 0 % negRisk, 99 % 2026; corpus check h1 median 0.001 passes; CTF-block anchor validated as the route).\n* **Q6b** — publishable (40 monthly observations, exact totals; class split for 2026 only).\n")
w("## Files\n")
w("`data/parquet/atlas/struct_markets.parquet` (851,083 markets + class), `struct_assets.parquet`, `struct_condmonth.parquet`, `struct_maker_month.parquet`, `struct_taker_month.parquet`, `struct_mintgroups_condmonth.parquet`, `struct_winner_offsets_archive.parquet`, `struct_ctf_resolution_time.parquet` (block-derived resolution time for 841,272 conditions), `struct_category_classmap.parquet`, `struct_q5_ctf_monthly/by_class/reconciliation_*`, `struct_q5_fills_monthly/by_class`, `struct_q6a_platform/corpus`, `struct_q6b_monthly/2026_by_class`. Scripts and logs: scratch `atlasC/` (`passA2.py`, `passB_merge.py`, `passC*_*.py`, `ctf_month.py`, `q5fills.py`, `q5ctf.py`, `q6a.py`, `q6b.py`, `calib.py`).\n")
open(f'{SC}/report.md','w').write("\n".join(out))
print(len("\n".join(out)))
